export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const CHANGE_COLOR = 'CHANGE_COLOR';
